### ISSUE TITLE
Proxy Type

### ISSUE THREAD

**Issue by hughsaffar** [serp-spider/http-client-curl#8]
Currently, it is not possible to define the proxy type (HTTP, SOCKS4 or SOCKS5). I tried to commit to a fork of core package but for some unknown reason it does not work!

**Comment by gsouf** [comment]
You are right, only http and https proxies are supported, I will add sock proxies very soon, it requires just a few though on my side to make sure everything is ok.

What does not work with your fork?

**Comment by hughsaffar** [comment]
I guess it was an issue with Github that I could not my commit. Now it's working. I add it also to this repo and send the PR.
